server:
  port: 7333
spring:
  profiles:
    active: dev
  application:
    name: cim-init
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jackson:
    #    date-format: yyyy-MM-dd HH:mm:ss
    #    time-zone: GMT+8
    #    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
ribbon:
  ReadTimeout: 900000
  ConnectTimeout: 900000